spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/OdysseyAi
    username: postgres
    password: megha
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      file: demo/docker-compose.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fcab58e9feef74de3828c68ff8e3e7f41fbc8f59
  access-token-expiration-ms: 900000

  refresh-token-expiration-ms: 604800000