spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: megha

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true